[package]
name = "linkdrop"
version = "0.1.0"
authors = ["eclipseeer <eclipseeer@gmail.com>"]
edition = "2018"

[dependencies]
near-sdk = "4.0.0-pre.2"
user = { path = "../user" }

[lib]
crate-type = ["cdylib", "rlib"]
